deathlog_strings_cn = {
	-- fonts
	main_font = "Fonts\\FRIZQT__.TTF",
	class_font = "Fonts\\FRIZQT__.TTF",
	death_alert_font = "Fonts\\FRIZQT__.TTF",
	mini_log_font = "Fonts\\FRIZQT__.TTF",
	menu_font = "Fonts\\FRIZQT__.TTF",
	deadliest_creature_container_font = "Fonts\\FRIZQT__.TTF",
	creature_model_quote_font = "Fonts\\FRIZQT__.TTF",
	-- death alerts messages
	death_alert_default_message = "<name> 的 <race> <class> 噶了\n<level> 级在 <zone> 死于 <source> 之手.",
	death_alert_default_fall_message = "<name> 的 <race> <class> 摔死了\n<level> 级在 <zone>",
	death_alert_default_drown_message = "<name> 的 <race> <class> 淹死了\n<level> 级在 <zone>",
	death_alert_default_slime_message = "<name> 的 <race> <class> has died from slime.\n<level> 级在 <zone>",
	death_alert_default_lava_message = "<name> 的 <race> <class> 被岩浆烫死了.\n<level> 级在 <zone>",
	death_alert_default_fire_message = "<name> 的 <race> <class> 被火烧死了.\n<level> 级在 <zone>",
	death_alert_default_fatigue_message = "<name> 的 <race> <class> 累死了.\n<level> 级在 <zone>",
	-- words
	corpse_word = "尸体",
	of_word = "的",
	minimap_btn_left_click = "|cFF666666Left Click:|r View log",
	minimap_btn_right_click = "|cFF666666Right Click:|r ",
	class_word = "职业",
	killed_by_word = "死于",
	zone_instance_word = "地点/副本",
	date_word = "时间",
	last_words_word = "遗言",
	death_word = "死亡",
	guild_word = "公会",
	race_word = "种族",
	name_word = "名字",
	show_heatmap = "显示热区",
	-- tables
	class_table = {
		Warrior = "战士",
		Rogue = "盗贼",
		Mage = "法师",
		Priest = "牧师",
		Paladin = "骑士",
		Shaman = "萨满",
		Druid = "小德",
		Warlock = "术士",
		Hunter = "猎人",
	},
	tab_table = {
		{ value = "ClassStatisticsTab", text = "职业统计" },
		{ value = "CreatureStatisticsTab", text = "种族统计" },
		{ value = "InstanceStatisticsTab", text = "副本统计" },
		{ value = "StatisticsTab", text = "地点统计" },
		{ value = "LogTab", text = "搜索" },
	},
	instance_tbl = {
		{ 33, "SHADOWFANGKEEP", "影牙城堡" },
		{ 36, "DEADMINES", "死亡矿井" },
		{ 34, "STORMWINDSTOCKADES", "监狱" },
		{ 43, "WAILINGCAVERNS", "哀嚎洞穴" },
		{ 47, "RAZORFENKRAUL", "剃刀沼泽" },
		{ 48, "BLACKFATHOMDEEPS", "黑暗深渊" },
		{ 90, "GNOMEREGAN", "诺莫瑞根" },
		{ 189, "SCARLETMONASTERY", "血色修道院" },
		{ 70, "ULDAMAN", "奥达曼" },
		{ 109, "SUNKENTEMPLE", "沉没的神庙" },
		{ 129, "RAZORFENDOWNS", "剃刀高地" },
		{ 209, "ZULFARAK", "祖尔法拉克" },
		{ 229, "BLACKROCKSPIRE", "黑石塔上层" },
		{ 230, "BLACKROCKDEPTHS", "黑石塔下层" },
		{ 289, "SCHOLOMANCE", "通灵学院" },
		{ 329, "STRATHOLME", "斯坦索姆" },
		{ 349, "MARAUDON", "玛拉顿" },
		{ 389, "RAGEFIRECHASM", "怒焰裂谷" },
		{ 429, "DIREMAUL", "厄运之槌" },
		{ 469, "BLACKWINGLAIR", "黑翼之巢" },
	},
	instance_map = {
		["影牙城堡"] = 33,
		["监狱"] = 34,
		["死亡矿井"] = 36,
		["哀嚎洞穴"] = 43,
		["剃刀沼泽"] = 47,
		["黑暗深渊"] = 48,
		["奥达曼"] = 70,
		["诺莫瑞根"] = 90,
		["沉没的神庙"] = 109,
		["剃刀高地"] = 129,
		["血色修道院"] = 189,
		["祖尔法拉克"] = 209,
		["黑石塔上层"] = 229,
		["黑石塔下层"] = 230,
		["通灵学院"] = 289,
		["斯坦索姆"] = 329,
		["玛拉顿"] = 349,
		["怒焰裂谷"] = 389,
		["厄运之槌"] = 429,
		["黑翼之巢"] = 469,
	},
	deathlog_zone_tbl = {
		["艾泽拉斯"] = 947,
		["杜隆塔尔"] = 1411,
		["莫高雷"] = 1412,
		["贫瘠之地"] = 1413,
		["卡利姆多"] = 1414,
		["东部王国"] = 1415,
		["奥特兰克山脉"] = 1416,
		["阿拉希高地"] = 1417,
		["荒芜之地"] = 1418,
		["诅咒之地"] = 1419,
		["提瑞斯法林地"] = 1420,
		["银松森林"] = 1421,
		["西瘟疫之地"] = 1422,
		["东瘟疫之地"] = 1423,
		["希尔斯布莱德丘陵"] = 1424,
		["辛特兰"] = 1425,
		["丹莫罗"] = 1426,
		["灼热峡谷"] = 1427,
		["燃烧平原"] = 1428,
		["艾尔文森林"] = 1429,
		["逆风小径"] = 1430,
		["暮色森林"] = 1431,
		["洛克莫丹"] = 1432,
		["赤脊山"] = 1433,
		["荆棘谷"] = 1434,
		["悲伤沼泽"] = 1435,
		["西部荒野"] = 1436,
		["湿地"] = 1437,
		["泰达希尔"] = 1438,
		["黑海岸"] = 1439,
		["灰谷"] = 1440,
		["千针石林"] = 1441,
		["石爪山脉"] = 1442,
		["凄凉之地"] = 1443,
		["菲拉斯"] = 1444,
		["尘泥沼泽"] = 1445,
		["塔纳利斯"] = 1446,
		["艾萨拉"] = 1447,
		["费伍德森林"] = 1448,
		["安戈洛环形山"] = 1449,
		["月光林地"] = 1450,
		["希利苏斯"] = 1451,
		["冬泉谷"] = 1452,
	},
	id_to_quote = {
		[6] = "Yiieeeee! Me run!",
		[38] = "I see those fools at the Abbey sent some fresh meat for us.",
		[40] = "You no take candle!",
		[80] = "Yiieeeee! Me run!",
		[95] = "Ah, a chance to use this freshly sharpened blade.",
		[97] = "Grrrr... fresh meat!",
		[98] = "More bones to gnaw on...",
		[117] = "Grrrr... fresh meat!",
		[121] = "Ah, a chance to use this freshly sharpened blade.",
		[122] = "Ah, a chance to use this freshly sharpened blade.",
		[123] = "Grrrr... fresh meat!",
		[124] = "Grrrr... fresh meat!",
		[212] = "I'll crush you!",
		[257] = "Yiieeeee! Me run!",
		[314] = "Aber?  Is that you...?  Oh...I'm so hungry, Aber!  SO HUNGRY!!",
		[315] = "I shall spill your blood, &lt;class&gt;!",
		[327] = "You no take candle!",
		[412] = "DARKSHIRE...I HUNGER!!",
		[423] = "Grrrr... fresh meat!",
		[424] = "Grrrr... fresh meat!",
		[426] = "Grrrr... fresh meat!",
		[429] = "Grrrr... fresh meat!",
		[430] = "Grrrr... fresh meat!",
		[431] = "Grrrr... fresh meat!",
		[432] = "Grrrr... fresh meat!",
		[433] = "Grrrr... fresh meat!",
		[434] = "Grrrr... fresh meat!",
		[445] = "Grrrr... fresh meat!",
		[446] = "Grrrr... fresh meat!",
		[452] = "Grrrr... fresh meat!",
		[475] = "You no take candle!",
		[476] = "You no take candle!",
		[478] = "Grrrr... fresh meat!",
		[481] = "Ah, a chance to use this freshly sharpened blade.",
		[500] = "Grrrr... fresh meat!",
		[504] = "Ah, a chance to use this freshly sharpened blade.",
		[568] = "Grrrr... fresh meat!",
		[580] = "Grrrr... fresh meat!",
		[589] = "Feel the power of the Brotherhood!",
		[590] = "Ah, a chance to use this freshly sharpened blade.",
		[639] = "And stay down!",
		[644] = "VanCleef pay big for you heads!",
		[646] = "D'ah! Now you're making me angry!",
		[8891] = "You can't hide from us.  Prepare to burn!",
		[706] = "I gonna make you into mojo!",
		[709] = "Me smash! You die!",
		[712] = "Grrrr... fresh meat!",
		[946] = "Killing you be easy.",
		[1007] = "Grrrr... fresh meat!",
		[1008] = "Grrrr... fresh meat!",
		[1009] = "Grrrr... fresh meat!",
		[1010] = "Grrrr... fresh meat!",
		[1011] = "Grrrr... fresh meat!",
		[1012] = "Grrrr... fresh meat!",
		[1051] = "Feel the power of the Dark Iron Dwarves!",
		[1052] = "Feel the power of the Dark Iron Dwarves!",
		[1053] = "Feel the power of the Dark Iron Dwarves!",
		[1115] = "Crush!",
		[1117] = "Crush!",
		[1121] = "I gonna make you into mojo!",
		[1123] = "I gonna make you into mojo!",
		[1157] = "A living human... soon to be a dead like me.",
		[1158] = "A living human... soon to be a dead like me.",
		[1161] = "Crush!",
		[1162] = "Crush!",
		[1163] = "Crush!",
		[1164] = "Crush!",
		[1165] = "Crush!",
		[1166] = "Crush!",
		[1167] = "Crush!",
		[1172] = "Me no run from &lt;class&gt; like you!",
		[1173] = "Me no run from &lt;class&gt; like you!",
		[1174] = "Me no run from &lt;class&gt; like you!",
		[1175] = "Me no run from &lt;class&gt; like you!",
		[1176] = "Me no run from &lt;class&gt; like you!",
		[1179] = "I'll crush you!",
		[1180] = "Me smash! You die!",
		[1197] = "Crush!",
		[1202] = "Me no run from &lt;class&gt; like you!",
		[1211] = "I'll cut you!",
		[1222] = "Wahehe! I'm taking you down with me!",
		[1236] = "You no take candle!",
		[9545] = "",
		[9547] = "",
		[1657] = "Here to visit the family?  Die, fool!",
		[1674] = "Grrrr... fresh meat!",
		[1675] = "Grrrr... fresh meat!",
		[1716] = "Tell the Warden this prison is ours now!",
		[1755] = "The Defias shall succeed! No meek adventurer will stop us!",
		[1756] = "A living legend...",
		[1770] = "The Sons of Arugal will rise against all who challenge the power of the Moonrage!",
		[1939] = "Grrrr... fresh meat!",
		[1940] = "Grrrr... fresh meat!",
		[1941] = "Grrrr... fresh meat!",
		[1942] = "Grrrr... fresh meat!",
		[10184] = "How fortuitous. Usually, I must leave my lair in order to feed.",
		[10373] = "What the... nobody cleanses a furbolg in MY camp!  Face the wrath of Xabraxxis!",
		[10440] = "I shall take great pleasure in taking this poor wretch's life!  It's not too late, she needn't suffer in vain.  Turn back and her death shall be merciful!",
		[2252] = "I'll crush you!",
		[2253] = "I'll crush you!",
		[2254] = "I'll crush you!",
		[2287] = "I'll crush you!",
		[2338] = "Carnage!  May I spill blood in His name!",
		[2339] = "Carnage!  May I spill blood in His name!",
		[2564] = "I'll crush you!",
		[2566] = "I'll crush you!",
		[2567] = "I'll crush you!",
		[2691] = "Attack, my sisters! The troll must not escape!",
		[2716] = "I'll crush you!",
		[2717] = "I'll crush you!",
		[2748] = "Awake, ye servants! Defend the Disks!",
		[10940] = "Leave this place!",
		[2775] = "You've plundered our treasures too long.  Prepare to meet your watery grave!",
		[10996] = "Be cleansed by blade, filth!",
		[11075] = "Human flesh... must feed!",
		[2949] = "Grrrr... fresh meat!",
		[2950] = "Grrrr... fresh meat!",
		[2951] = "Grrrr... fresh meat!",
		[11443] = "I'll crush you!",
		[3275] = "I am slain!  Summon Verog!",
		[3276] = "You will be easy prey, &lt;class&gt;.",
		[3277] = "You will be easy prey, &lt;class&gt;.",
		[3278] = "My talons will shred your puny body, Orc.",
		[3282] = "There's the stolen shredder! Stop it or Lugwizzle will have our hides!",
		[3284] = "Get away from there!",
		[3285] = "Get away from there!",
		[11502] = "BY FIRE BE PURGED!",
		[3395] = "I am summoned!  Intruders, come to my tent and face your death!",
		[3397] = "I am slain!  Summon Verog!",
		[3667] = "Finally, my soul may rest... Oh, dearest Cerellean...",
		[3671] = "None can stand against the Serpent Lords!",
		[11886] = "Well, well. Looks like we got ourselves some competition. Get 'em boys!",
		[3927] = "I can't believe it! You've destroyed my pack... Now face my wrath!",
		[3975] = "Ah - I've been waiting for a real challenge!",
		[3976] = "At your side, milady!",
		[4003] = "I think the sounds came from over here. We'd better check it out.",
		[4004] = "What's going on here? Piznik! I knew we shouldn't have let you stick around!",
		[4062] = "No sign of the final explosives shipment to the west either.  Where are those lollygaggers?",
		[4275] = "Another falls!",
		[4287] = "The light condemns all who harbor evil.  Now you will die!",
		[4299] = "The light condemns all who harbor evil.  Now you will die!",
		[4301] = "The light condemns all who harbor evil.  Now you will die!",
		[4484] = "Assassins from that cult you found... Let's get moving before someone else finds us out here.",
		[4494] = "The light condemns all who harbor evil.  Now you will die!",
		[4540] = "The light condemns all who harbor evil.  Now you will die!",
		[12858] = "Everyone ready?",
		[12918] = "No!  You cannot be stronger than the Foulweald!  No!!",
		[12922] = "Alright I'm going! Stop yelling!",
		[4966] = "Please... please... Miss Proudmore. I didn't mean to...",
		[4969] = "All right, boss. You sure though? Just seems like a waste of good practice.",
		[4971] = "Whoa! This is way more than what I bargained for, you're on your own, Slim!",
		[5234] = "I'll crush you!",
		[5239] = "Me smash! You die!",
		[5240] = "I'll crush you!",
		[5255] = "Grrrr... fresh meat!",
		[5474] = "I'll crush you!",
		[6090] = "Ok, enough!  I give up!",
		[6180] = "Feel the power of the Brotherhood!",
		[6182] = "You won't ruin my lands, you scum!",
		[6221] = "A foul trogg if ever I saw one.  Die!",
		[6238] = "Ready when you are, warrior.",
		[6784] = "Okay, okay... gimmie a minute to rest now. You gone and beat me up good.",
		[7033] = "I'll crush you!",
		[7603] = "A foul trogg if ever I saw one.  Die!,",
	},
}
